### ISSUE TITLE
How to make a "components" plugin?

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/plugin-template#4]
Hi,
When creating a plugin, I see there are:
adaptator
decorator
event
transition
...but what about a plugin that provides components/widgets?

**Comment by dagnelies** [comment]
Hi,

there is still the pull request waiting there:
https://github.com/ractivejs/plugin-template/pull/5

**Comment by Rich-Harris** [comment]
@dagnelies sorry about that! merged

**Comment by dagnelies** [comment]
@Rich-Harris 
While we're at it, there are a few waiting there too ;)
https://github.com/ractivejs/Ractive-decorators-sortable/pulls
